version: '3.3'

services:
#   db:
#     image: mysql:5.7
#     volumes:
#       - dbdata:/var/lib/mysql
#     restart: always
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: univille
#       MYSQL_DATABASE: projetospring
#       MYSQL_USER: univille
#       MYSQL_PASSWORD: univille
   appweb:
#     depends_on:
#       - db
     image: projetospring:latest
     ports:
       - "8081:80"
     restart: always
     external_links:
        - db:server-mysql
     environment:
       DATABASE_URL: jdbc:mysql://server-mysql:3306/projetospring?reconnect=true&user=univille&password=univille
#volumes:
#    dbdata:
